# Generated by Django 5.2.1 on 2025-06-08 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ddabb1f-e940-44c2-9c01-474971348149'), primary_key=True, serialize=False, unique=True),
        ),
    ]
