# Generated by Django 5.2.1 on 2025-06-08 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c14746c6-33c6-477c-a0fe-7826270396cd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
