# Generated by Django 5.2.1 on 2025-06-11 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_name_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('staff', 'STAFF'), ('user', 'USER')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0abdd6e5-0ddf-4577-a483-2136adcaf52f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
